### ISSUE TITLE
Invalid mapping: Negative column number

### ISSUE THREAD

**Issue by narthollis** [webpack-contrib/sass-loader#351] opened 2017-01-20 01:20 UTC
When running `webpack -p` I am getting errors that appear to be related to producing sourcemaps. When i set `sourceMap: false` for `sass-loader` the build runs cleanly.

Stack trace follows:
```
Error: Invalid mapping: {"generated":{"line":1,"column":24989},"source":"webpack:///Work/Platform/Web/Web.App/assets/css/Work/Platform/Web/Web.App/Work/Platform/Web/Web.App/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_clearfix.scss","original":{"line":15,"column":-12},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-map-generator.js:101:12)
    at C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-node.js:345:13
    at SourceNode_walk [as walk] (C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-node.js:224:9)
    at SourceNode_walk [as walk] (C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-node.js:220:13)
    at SourceNode_walk [as walk] (C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-node.js:220:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (C:\Work\Platform\Web\Web.App\node_modules\source-map\lib\source-node.js:336:8)
    at ConcatSource.proto.sourceAndMap (C:\Work\Platform\Web\Web.App\node_modules\webpack-sources\lib\SourceAndMapMixin.js:28:32)
    at Compilation.<anonymous> (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins1 (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:14)
    at self.applyPluginsAsync.err (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\Compilation.js:605:11)
    at next (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.compilation.plugin (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:140:5)
    at Compilation.applyPluginsAsyncSeries (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\Compilation.js:601:10)
    at next (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (C:\Work\Platform\Web\Web.App\node_modules\extract-text-webpack-plugin\index.js:316:4)
    at Compilation.applyPluginsAsyncSeries (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
    at sealPart2 (C:\Work\Platform\Web\Web.App\node_modules\webpack\lib\Compilation.js:597:9)
    at next (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (C:\Work\Platform\Web\Web.App\node_modules\extract-text-webpack-plugin\index.js:292:5)
    at C:\Work\Platform\Web\Web.App\node_modules\extract-text-webpack-plugin\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\Work\Platform\Web\Web.App\node_modules\extract-text-webpack-plugin\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (C:\Work\Platform\Web\Web.App\node_modules\extract-text-webpack-plugin\node_modules\async\lib\async.js:209:22)
    at ExtractTextPlugin.<anonymous> (C:\Work\Platform\Web\Web.App\node_modules\extract-text-webpack-plugin\index.js:244:10)
    at Compilation.applyPluginsAsyncSeries (C:\Work\Platform\Web\Web.App\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
```

**Comment by karol-f** [comment] 2017-01-26 11:26
+1

```
Error: Invalid mapping: {"generated":{"line":11,"column":21330},"source":"webpack:///src/demo/styles/node_modules/foundation-sites/scss/util/_mixins.scss","original":{"line":139,"column":-1},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:345:13
    at SourceNode_walk [as walk] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:224:9)
    at SourceNode_walk [as walk] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_walk [as walk] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_walk [as walk] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/Users/Karol/www/projects/project/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:336:8)
    at ConcatSource.proto.sourceAndMap (/Users/Karol/www/projects/project/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:32)
    at Compilation.<anonymous> (/Users/Karol/www/projects/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/Users/Karol/www/projects/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/Karol/www/projects/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins1 (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Users/Karol/www/projects/project/node_modules/webpack/lib/Compilation.js:605:11)
    at next (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/Users/Karol/www/projects/project/node_modules/webpack/lib/BannerPlugin.js:45:5)
    at next (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:140:14)
    at Compilation.compilation.plugin (/Users/Karol/www/projects/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:5)
    at Compilation.applyPluginsAsyncSeries (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/Users/Karol/www/projects/project/node_modules/webpack/lib/Compilation.js:601:10)
    at next (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/index.js:314:4)
    at Compilation.applyPluginsAsyncSeries (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/Users/Karol/www/projects/project/node_modules/webpack/lib/Compilation.js:597:9)
    at next (/Users/Karol/www/projects/project/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/index.js:290:5)
    at /Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:936:13)
    at /Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:840:16
    at /Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/index.js:274:6
    at /Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:936:13)
    at /Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:840:16
    at /Users/Karol/www/projects/project/node_modules/extract-text-webpack-plugin/index.js:264:9
    at rebuilding.forEach.cb (/Users/Karol/www/projects/project/node_modules/webpack/lib/Compilation.js:475:29)
    at Array.forEach (native)
    at callback (/Users/Karol/www/projects/project/node_modules/webpack/lib/Compilation.js:475:15)
    at processModuleDependencies (/Users/Karol/www/projects/project/node_modules/webpack/lib/Compilation.js:494:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by maggo** [comment] 2017-02-13 13:10
Can confirm, same error and stack trace. It's also fixed by setting the `sourceMap` option in css-loader to false

**Comment by jhnns** [comment] 2017-02-13 14:37
Please provide a small example repository that demonstrates the error. Could you also check if the error is still there without the sass-loader?

**Comment by karol-f** [comment] 2017-02-13 14:39
@jhnns My other files without sass-loader work fine with source maps. Also this only happens when I build for production so I'm using `extractTextWebpackPlugin` and `css-loader`.

**Comment by maggo** [comment] 2017-02-13 15:32
Hi @jhnns in my case the error seems to be `extract-text-webpack-plugin` in conjunction with the `minimize` setting from `LoaderOptionsPlugin` see my example repo: https://github.com/maggo/sass-loader-sourcemaps-bug

**Comment by jhnns** [comment] 2017-02-13 19:15
@maggo thanks for the example repo. The processed source map contains a negative column number. I don't know how we can fix that since this column numbers come from node-sass.

I've tried to compile the `index.scss` with node-sass itself and it seems to work, so maybe that's an issue with webpack's source map consumer :(

I think, this is also related to #272

**Comment by ash14** [comment] 2017-02-15 06:06
I'm having the same issue. If anyone's interested I have a simpler case reproduced in [this repo](https://github.com/ash14/sass-loader-bug)

One possible workaround is to use `outputStyle: 'compact'` instead of `compressed`

**Comment by kfbow** [comment] 2017-02-22 19:57
+1

**Comment by albertogasparin** [comment] 2017-03-02 17:25
I'm also having this issue. @ash14 Changing the `outputStyle` does not make any difference (tried all options). The file causing the error is imported from the node_modules folder ([source here](https://github.com/albertogasparin/pollicino-ui/blob/master/scss/_mixins.scss))

```
Error: Invalid mapping: {"generated":{"line":2233,"column":0},"source":"/.../node_modules/pollicino-ui/scss/_mixins.scss","original":{"line":64,"column":-1},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/.../node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/.../node_modules/source-map/lib/source-map-generator.js:101:12)
    ...
```

**Comment by jhnns** [comment] 2017-03-03 10:40
@albertogasparin awesome! This is a good starting point to locate the error. Unfortunately, I don't have time for that now, but I would be glad if someone of you could tackle it.

Crazy, I've never seen mixins and `&` used together:

```scss
@mixin FormField {
  position: relative;
  display: flex;
  line-height: $Pollicino-FormField-height;

  &-label {     // <---- that's where the error is coming from
```

**Comment by karol-f** [comment] 2017-03-03 10:45
@jhnns It's pretty common. I've checked and in my error Foundation CSS mixins also have `&` in `_mixins.scss` - https://github.com/zurb/foundation-sites/blob/develop/scss/util/_mixins.scss.

**Comment by b4cedev** [comment] 2017-03-15 08:45
+1 
Just ran into the same problem: with webpack 2 due to file foundation-si
  tes/scss/components/_button.scss from bower install (v.6.2.4):

`Invalid mapping: {"generated":{"line":2828,"column":2},"source":"webpack:///bower_components/foundation-si
  tes/scss/components/_button.scss","original":{"line":155,"column":-10},"name":null}`

Only "compressed" output triggered it, "compact" & "verbose" are working.

**Comment by zeusbangayan** [comment] 2017-03-17 13:59
I have the same problem:

{
							loader: "sass-loader",
							options: {
								sourceMap: true,
								outputStyle: PROD ? "compressed" : "nested"								
							}
						},

Compressed is NOT working.

I agree with @b4cedev, only Compact and verbose are working.

**Comment by Vinnl** [comment] 2017-03-19 14:30
(I've hesitated posting this since two people already seem to have observed the same, but just in case, another confirmation with details...)

I'm running into this too, and with a similar configuration: ExtractTextPlugin, Sass and PostCSS. Indeed adding an `outputStyle` of `compact` made the error go away. The error message points to a line containing only `&:focus {`, also located inside a mixin (in Foundations `_text.scss`).

**Comment by Andrey7287** [comment] 2017-04-01 11:25
Any solution ?

outputStyle: 'compact' doesn`t work for me :( .

**Comment by narthollis** [comment] 2017-04-11 23:51
It appears this may be related to https://github.com/sass/libsass/issues/2312

**Comment by evilebottnawi** [comment] 2017-04-23 15:17
Confirmed, it is related to https://github.com/sass/libsass/issues/2312, need fix in `node-sass`

**Comment by evilebottnawi** [comment] 2017-05-23 10:13
Close here, not related to `sass-loader`, we need to search `C++` superman and fix it `libsass`

**Closed by evilebottnawi** 2017-05-23 10:13 UTC
Labels: priority: 2 (urgent), type: Bug

**Comment by lili21** [comment] 2017-06-19 09:18
@Andrey7287
> setting the sourceMap option in css-loader to false

**Comment by iwinux** [comment] 2017-07-05 06:50
Temp fix:

```javascript
{
  test: /\.scss$/,
  use: [
    'style-loader',
    { loader: 'css-loader', options: { sourceMap: true } },
    { loader: 'sass-loader', options: { sourceMap: false } },  // disable source map
  ]
}
```

At least we can see the original filename of CSS styles...

**Comment by mishelen** [comment] 2017-09-06 01:54
In my case value of column number is equal to length of mixin name. I use expanded outputStyle

```
"source":"/app/node_modules/foundation-sites/scss/forms/_text.scss",
"original":{"line":111,"column":-12},"name":null}
```
And that mixin:

```scss
@mixin form-element {
//....
  &:focus {}
}
```
May be it occasion)) But logically, what we do with sass placeholder? Replace! even with mixin name, isnt it)) Also name includes hyphen (negative, minus), Foundation seems to be loves hyphens in names))

**Comment by Slapbox** [comment] 2017-09-06 02:05
Regarding, "I used expanded outputStyle"

@mishelen Can you elaborate on what you mean by this? Is there a way to have it show additional details on failure? I've not been able to track down the source of my occurrence.

**Comment by mishelen** [comment] 2017-09-06 02:37
Ok, part of related webpack config is:

```js
// ...
devtool: process.env.NODE_ENV === 'PRODUCTION' ? 'source-map' : 'inline-source-map',
// ...
{
     test: /\.scss$/, use: ExtractTextPlugin.extract({
     fallback: 'style-loader',
     use: [{
     loader: 'css-loader', options: {
          sourceMap: true
     }
}, {
     loader: 'postcss-loader',
     options: {
     sourceMap: true,
     plugins: function () {
          return [
               autoprefixer({
                    cascade: false,
                         browsers: ['last 2 versions']
                    })
               ];
          }
     }
}, {
     loader: 'sass-loader', options: {
          sourceMap: true,
          outputStyle: 'expanded',
          includePaths: [
               path.resolve(ROOT_PATH, 'node_modules/foundation-sites/scss')
          ]
     }
}]
```

I'm have just noticed **that webpack without `-p` flag compiles styles nicely.** This flag launch webpack's  Uglify plugin, as all known.

Stacktrace of error is repeated locally and on Heroku:

```
/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-map-generator.js:289
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":1,"column":39305},"source":"/home/mishelen/projects/nonameapp/node_modules/foundation-sites/scss/forms/_text.scss","original":{"line":111,"column":-12},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-node.js:351:13
    at SourceNode_walk [as walk] (/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-node.js:230:9)
    at SourceNode_walk [as walk] (/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_walk [as walk] (/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/home/mishelen/projects/nonameapp/node_modules/source-map/lib/source-node.js:342:8)
    at ConcatSource.proto.sourceAndMap (/home/mishelen/projects/nonameapp/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:32)
    at getTaskForFile (/home/mishelen/projects/nonameapp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/home/mishelen/projects/nonameapp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at /home/mishelen/projects/nonameapp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (/home/mishelen/projects/nonameapp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/home/mishelen/projects/nonameapp/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/home/mishelen/projects/nonameapp/node_modules/webpack/lib/Compilation.js:661:11)
    at next (/home/mishelen/projects/nonameapp/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/home/mishelen/projects/nonameapp/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
    at Compilation.applyPluginsAsyncSeries (/home/mishelen/projects/nonameapp/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/mishelen/projects/nonameapp/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/home/mishelen/projects/nonameapp/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/home/mishelen/projects/nonameapp/node_modules/extract-text-webpack-plugin/dist/index.js:272:11)
    at Compilation.applyPluginsAsyncSeries (/home/mishelen/projects/nonameapp/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/home/mishelen/projects/nonameapp/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/home/mishelen/projects/nonameapp/node_modules/tapable/lib/Tapable.js:202:11)
    at /home/mishelen/projects/nonameapp/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /home/mishelen/projects/nonameapp/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/mishelen/projects/nonameapp/node_modules/async/dist/async.js:998:13)
    at /home/mishelen/projects/nonameapp/node_modules/async/dist/async.js:906:16
    at /home/mishelen/projects/nonameapp/node_modules/extract-text-webpack-plugin/dist/index.js:224:15

```

**Comment by Slapbox** [comment] 2017-09-06 14:20
@mishelen Thank you. This is a hugely helpful reference point in trying to pin down my own instance of this issue.

**Comment by denyo** [comment] 2017-09-11 07:36
Here is what I just figured out as a workaround.
The location where I had the error with `column: -1` looked like this:
```
@mixin flexWithCols {
  display: flex;

  &__col {
    ... // more styles here
  }
}
```

The error appeared on the line with `&__col {` which is intended by 2 spaces. 
Now simply by changing the indentation to 4 spaces fixes the error:
```
@mixin flexWithCols {
  display: flex;

    &__col {
      ... // more styles here
    }
}
```

**Comment by jotavejv** [comment] 2017-10-13 20:27
If the problems are related to sass, it is probably due to "compressed" outputStyle. I figured it out just change compressed to "compact".

**Comment by ingro** [comment] 2017-10-17 10:57
Thanks @jotavejv , that fixed my error!

**Comment by drewlustro** [comment] 2017-10-18 15:41
+1 on this... anyone know how to keep `sourceMap: true` for both the `css-loader` and `sass-loader` ?

**Comment by jcapozzi** [comment] 2017-11-30 16:35
Google brought me here after searching for a solution for sass/libsass#2312 which is sadly locked so I can't comment there but maybe this will help someone else:

Adding a space after the & after getting the error fixed it for me.

Before:
`
&:hover {
  color: red;
}
`

After:
`
& :hover {
 color: red;
}
`

**Comment by HIMISOCOOL** [comment] 2017-12-17 21:52
like @jotavejv changing that option did stuff.
See [here ](https://github.com/sass/node-sass#outputstyle) for possible values and try one.
Expanded worked for me

**Comment by leocaseiro** [comment] 2018-01-12 01:28
@jcapozzi that's the only solution that fixed my issue!

Many many many thanks!

Now I'm going to submit a PR to https://github.com/material-components/material-components-web/

**Comment by bilalmalkoc** [comment] 2020-10-04 11:33
This worked for me.

    {
        test: /\.(sa|sc|c)ss$/,
        use: [
            MiniCssExtractPlugin.loader,
            'css-loader',
            {
                loader: 'postcss-loader',
                options: {
                    sourceMap: true,
                    postcssOptions: {
                        plugins: [autoprefixer()],
                    },
                },
            },
            'sass-loader',
        ],
    },

**Comment by orassayag** [comment] 2021-01-17 11:32
I had the same issue, my problem was at `@import url('./all.css');`
I changed it to `@import './all.css';` and the error gone!
