### ISSUE TITLE
sass-loader failing to find mixin files 

### ISSUE THREAD

**Issue by icf-mrankin** [webpack-contrib/sass-loader#806] opened 2020-02-27 21:30 UTC
- Operating System: MacOS 10.14.6
- Node Version: 11.15.0
- NPM Version: 6.13.4
- webpack Version: 4.41.6
- sass-loader Version: 8.0.2

### Expected Behavior

running the webpack-dev-server/sass-loader should compile css

### Actual Behavior

links in the @material node_modules directories pointing to other mixin files fails to resolve.  I found that if I prepend a tilde ~ to the @use link, it gets found.

### Code

[https://gist.github.com/icf-mrankin/6bea78ef2787d893d82e6c019b790222](url)

### How Do We Reproduce?

After doing npm i, run npm start.

running nix sass app.scss app.css --load-path=node_modules complies fine.

This is pretty much straight from the Getting Started document [https://material.io/develop/web/docs/getting-started/](url)

**Comment by evilebottnawi** [comment] 2020-02-28 10:05
Please provide reproducible test repo

**Comment by evilebottnawi** [comment] 2020-02-28 10:06
Duplicate of #804 Please use search before posting a issue

**Closed by evilebottnawi** 2020-02-28 10:06 UTC
