### ISSUE TITLE
Scss from node_modules didn't go in vendor chunk

### ISSUE THREAD

**Issue by Alex-Ferreli** [webpack-contrib/sass-loader#667] opened 2019-02-20 13:29 UTC
* Operating System: Ubuntu 18.04
* Node Version: 11.8.0
* NPM Version: 6.5.0
* webpack Version: 4.29.5
* sass-loader Version: 7.1.0

### Expected Behavior
Webpack should place .scss imported files (bootstrap .scss for example) inside vendor.css chunk.

### Code

If import is done in js, like this:
```js
import 'bootstrap/scss/bootstrap-reboot.scss';
```
Resulting css generated by sass go in vendor chunk.

But if i import other scss file like this:
```js
@import '~bootstrap/scss/bootstrap-reboot.scss';
```
then the generated css go in main chunk.

I can't do all imports in js, because some scss require some variables in other scss files (like bootstrap)

### How Do We Reproduce?
Just create a new app with create react app -> install node-sass and bootstrap -> create a scss file and import bootstrap -> do a build to see that the css is in main chunk and not in vendor.

Should i create a repo for this issue?

Thanks in advance!

**Comment by evilebottnawi** [comment] 2019-02-20 13:31
@Alex-Ferreli not sure it is related to `scss-loader`, we just generate `scss` -> `css`, splitting chunks is part of webpack, can you create minimum reproducible test repo?

**Comment by Alex-Ferreli** [comment] 2019-02-20 13:59
This is the repo to reproduce the bug. Just comment/decomment the lines in src/index.js file.
https://github.com/Alex-Ferreli/sass-import-vendor-chunk-issue

Thanks!

**Comment by evilebottnawi** [comment] 2019-02-20 14:01
@Alex-Ferreli i will see in near future

**Comment by evilebottnawi** [comment] 2019-02-25 15:50
@Alex-Ferreli please provide you webpack config

**Comment by Alex-Ferreli** [comment] 2019-02-25 16:12
@evilebottnawi Just eject the project, the issue persist

**Comment by evilebottnawi** [comment] 2019-02-25 16:18
@Alex-Ferreli without `~` generated css always in `app` chunk? With `~` in `vendor`, right? Splitting chunks  applied only in `prod` mode so some modules can be moved from `app` in `vendor` chunk in `prod` mode

**Comment by Alex-Ferreli** [comment] 2019-02-25 16:42
@evilebottnawi when i do import in `.scss` file the code always go in `app` chunk. Maybe webpack place the content of generated css in `app` chunk because i'm importing main scss file from `src`? And webpack didn't recognise `scss @import` path.

**Comment by evilebottnawi** [comment] 2019-02-25 16:59
@Alex-Ferreli in `prod` env code always moved to `vendor` chunk, right? Because it is expected behaviour

**Comment by Alex-Ferreli** [comment] 2019-02-25 17:24
@evilebottnawi when i do a build, NODE_ENV is set to `production`, right? There is another variable to set?

**Comment by evilebottnawi** [comment] 2019-02-26 09:59
@Alex-Ferreli you should set `mode: production`, but in many boilerplate is it same as `NODE_ENV`

**Comment by felixfbecker** [comment] 2019-02-27 13:30
I would like to make sure that if I have two JS files that both import Sass files, where these Sass files both `@import` e.g. Bootstrap, that Bootstrap is not included twice in the bundle but code-split into a common chunk. It seems sass-loader doesn't allow webpack to do this

**Comment by evilebottnawi** [comment] 2019-03-04 09:24
@felixfbecker `splitChunks` not related to `sass-loader`, better ask this question/problem in `webpack` repo, we just compile `sass`/`scss` to `css`, we don't do more. Closing. Feel free to create issue in `webpack` or you can use `stackoverflow`/`gitter` for helping

**Closed by evilebottnawi** 2019-03-04 09:24 UTC

**Comment by felixfbecker** [comment] 2019-03-04 09:27
Wouldn't splitChunks require sass-loader to expose the module tree to webpack? My understanding is that currently it just exposes the entire bundle to webpack, with all `@import`s already resolved.

**Comment by evilebottnawi** [comment] 2019-03-04 09:29
@felixfbecker module do `css-loader`, `sass-loader` just compile `sass`/`scss` to css, all `@import`s (for `sass`/`scss`) already resolved after `sass-loader`

**Comment by felixfbecker** [comment] 2019-03-04 09:34
Yes, that's my point. It doesn't seem possible to solve from webpack's side because sass-loader already resolves all imports.

**Comment by Alex-Ferreli** [comment] 2019-03-04 10:23
So `sass-loader` place generated `css` as the imported file from JS right? Maybe `sass-loader` should use imported `scss` from `node_modules` to generate local `css` code without put the code from `node_modules`, and tell to `webpack` those files imported in `scss` files.

**Comment by evilebottnawi** [comment] 2019-03-04 11:17
@Alex-Ferreli 
> So sass-loader place generated css as the imported file from JS right?

No, it is do `css` loader. `sass-loader` (compile `sass`/`scss` as `css`) -> `css-loader` (compile css to js file)
