### ISSUE TITLE
Module not found: Can't resolve './alert' in '/mydirectory/node_modules/bootstrap/scss'

### ISSUE THREAD

**Issue by adrian2020my** [webpack-contrib/sass-loader#567] opened 2018-05-06 11:32 UTC
I use @import "~bootstrap/scss/bootstrap"; in my custom.scss but when webpack tries to compile, the following error appears:

> Failed to compile.

>./node_modules/bootstrap/scss/bootstrap.scss
>Module not found: Can't resolve './alert' in 'mydirectory/node_modules/bootstrap/scss'

Please kindly advise on resolving this issue as I'm not able to customise my css using mixins from bootstrap.

My webpack.config file is as below:
[webpack.config.txt](https://github.com/webpack-contrib/sass-loader/files/1977573/webpack.config.txt)

**Comment by evilebottnawi** [comment] 2018-05-06 11:50
@adrian2020my please provide minimum reproducible test repo, we can't help without structure and version bootstrap, thanks

**Comment by adrian2020my** [comment] 2018-05-06 12:17
Thanks for the reply. @evilebottnawi Here is the repo: https://github.com/adrian2020my/webpackBootstrap

**Comment by adrian2020my** [comment] 2018-05-06 13:52
I lowered the version of sass-loader to 6.0.7 but it still doesn't compile.

**Comment by evilebottnawi** [comment] 2018-05-06 14:04
@adrian2020my `includePaths: ['src', 'node_modules']` for sas-loader options?

**Comment by adrian2020my** [comment] 2018-05-06 14:05
@evilebottnawi Sorry, it works. I managed to compile it, had to remove the previous version first before reinstalling the older version of sass-loader. May I know why it doesn't compile in the latest version?

**Comment by evilebottnawi** [comment] 2018-05-06 14:12
@adrian2020my https://github.com/webpack-contrib/sass-loader/issues/556 on next week i will try to find time on fix it, just regression

**Comment by evilebottnawi** [comment] 2018-05-06 14:13
Can we close issue?

**Comment by adrian2020my** [comment] 2018-05-06 14:13
@evilebottnawi  sorry for my previous comment, it still doesn't work. When I tested the working one, I accidentally removed the import "~bootstrap/scss/bootstrap"; After I tried it, still doesn't compile.

**Comment by adrian2020my** [comment] 2018-05-06 14:14
@evilebottnawi Currently, I'm back to square one. ./node_modules/bootstrap/scss/bootstrap.scss
Module not found: Can't resolve './alert' in '/frontend/node_modules/bootstrap/scss'

**Comment by evilebottnawi** [comment] 2018-05-06 14:16
@adrian2020my https://github.com/webpack-contrib/sass-loader/issues/567#issuecomment-386881697?

**Comment by adrian2020my** [comment] 2018-05-07 16:10
After struggling with this issue the entire day, I managed to go around my problem by following the instructions in facebook/create-react-app:  https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc . I was not able to fully resolve my issue in regards to the importing the bootstrap module. Maybe facebook has configured webpack to the point where it's hard to directly import sass file from node_modules/ to the src directory.

**Comment by jsg2021** [comment] 2018-05-14 18:51
This must be a duplicate of #566

**Comment by evilebottnawi** [comment] 2018-05-28 11:30
@jsg2021 yep, duplicate thanks!

**Closed by evilebottnawi** 2018-05-28 11:30 UTC

**Comment by vegagame** [comment] 2020-05-02 23:42
> 1 .import own scss langage not css langage so app.css should be app.scss
> 2. add .addStyleEntry('css/app', './assets/css/app.scss') in webpack.config.js file
> 3. be sure node-sass et sass-loader are installed(yarn add -D node-sass sass-loader)

Good! It work also for me! :)
