### ISSUE TITLE
Error to compile .sass syntax

### ISSUE THREAD

**Issue by brunoravanhani** [webpack-contrib/sass-loader#361] opened 2017-02-02 18:17 UTC
When i add bulma framework with .sass syntax have this error:

`Media query expression must begin with '('`

 Without this, works fine.

My loader: 
```
{
        test: [/\.[s]css$/, /\.sass$/],
        loader: ExtractTextPlugin.extract({
                loader: ["css-loader", "sass-loader"]
        })
}
```

Any suggestions?

**Comment by thibmaek** [comment] 2017-03-08 11:02
Seeing the same issue over here

**Comment by jhnns** [comment] 2017-03-08 13:24
The file must have the `sass` extension if it's written in sass syntax. Try to narrow down the exact file, that is causing the issue and try to compile it with `node-sass`. Does it work with `node-sass`?

**Comment by emericmourot** [comment] 2017-03-16 23:01
Did you try to compile your file in sass syntax with ?indentedSyntax parameter set ?
`loader: ["css-loader", "sass-loader?indentedSyntax"]`

**Comment by jhnns** [comment] 2017-03-16 23:32
You don't need to set the option explicitly anymore. The sass-loader derives it automatically for files ending on `.sass`

**Comment by evilebottnawi** [comment] 2017-05-03 10:38
@brunoravanhani seems your have wrong `sass` syntax, can your provide `sass` example file?

**Comment by brunoravanhani** [comment] 2017-05-03 15:00
The code was in a framework called [bulma](http://bulma.io/), but i changed my framework in that project.

**Comment by evilebottnawi** [comment] 2017-05-03 15:29
@brunoravanhani As I understand the problem is no more? Can we close this issue?

**Comment by brunoravanhani** [comment] 2017-05-03 17:09
Yes, can close.

**Closed** 2017-05-03 17:10 UTC
Labels: flag: Needs more info
