### ISSUE TITLE
Is there a way to enforce a file extension precedence

### ISSUE THREAD

**Issue by sharlayoub** [webpack-contrib/sass-loader#349] opened 2017-01-16 23:19 UTC
I want to enforce file loading precedence like ['.ext.scss', '.scss'] something that resembles webpack resolve.extenions or node require,extensions? Any ideas?

**Comment by jhnns** [comment] 2017-02-08 11:17
Have you tried fiddling around with webpack's resolving options? The sass-loader uses webpack's resolving engine, so that should work (in theory). I haven't tests for that, though.

**Comment by evilebottnawi** [comment] 2017-05-03 18:06
@sharlayoub can your provide minimal reproducible test repo. `test: /\.scss$/` already handle `.ext.scss` files.

**Comment by evilebottnawi** [comment] 2017-06-29 12:33
@sharlayoub Problem solved? If not, then you can provide more information?

**Comment by evilebottnawi** [comment] 2017-06-29 12:50
@sharlayoub example https://github.com/ctrine/webpack-settings/blob/master/packages/shared/src/rules/sass-module.js how use `.module.scss`

**Comment by evilebottnawi** [comment] 2017-06-29 12:51
Closing due to inactivity. Feel free to reopen if example above don't solve your problems. Thanks!

**Closed by evilebottnawi** 2017-06-29 12:51 UTC
Labels: flag: Needs more info
