### ISSUE TITLE
Usage with yarn workspaces incorrectly identifies modules

### ISSUE THREAD

**Issue by zposten** [webpack-contrib/sass-loader#820] opened 2020-03-31 21:02 UTC
- Operating System: macOS v10.15.3
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.42.1
- sass-loader Version: 8.0.2

### Expected Behavior

When using sass-loader in combination with yarn workspaces, a module should be uniquely identified as itself, regardless of if it is referenced by a relative import path (e.g. `./foo`) or an "absolute" import path that is located in one of its configured `includePaths` (e.g. `@test/foo`).

### Actual Behavior

If Sass module-A that is referred to both by a relative and absolute path configures another module-B, then `sass-loader` incorrectly throws an error saying that module-B is "already loaded, so it can't be configured using 'with'", even though module-B is only loaded a single time, within module-A.

Notice that both the new load and original load in the below error point to the same exact file, but the paths are different. One paths through the `packages/` directory and the other passes through the `node_modules` directory. Because of how yarn workspaces works, the file located in `node_modules/` is actually a simlinked version of the file located in `packages/`.  Please see the reproduction repo linked below for more context.

```
ERROR in ./packages/third/_index.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: This module was already loaded, so it can't be configured using "with".
  ┌──> node_modules/@test/second/_variables.scss
1 │ ┌ @forward '@test/first' with (
2 │ │   $primary: rebeccapurple !default,
3 │ │ );
  │ └─^ new load
  ╵
  ┌──> packages/second/_variables.scss
1 │ ┌ @forward '@test/first' with (
2 │ │   $primary: rebeccapurple !default,
3 │ │ );
  │ └─^ original load
  ╵
  node_modules/@test/second/_variables.scss 1:1  @use
  node_modules/@test/second/_functions.scss 1:1  @use
  /Users/zach/dev/test/sass-re-forward/packages/third/_index.scss 2:1                                      root stylesheet
 @ multi ./packages/third/_index.scss main[0]
```

I think it's important to note that using `sass` directly avoids this issue, and also that changing all relative import paths to absolute import paths also works around this issue.

### Code

[webpack.config.js](https://github.com/zposten/sass-loader-yarn-workspace-path-issue/blob/master/webpack.config.js)

### How Do We Reproduce?

Use [this repo](https://github.com/zposten/sass-loader-yarn-workspace-path-issue).  The README has detailed instructions for comparing the output of `sass` against `webpack`.

```
git clone https://github.com/zposten/sass-loader-yarn-workspace-path-issue.git
cd sass-loader-yarn-workspace-path-issue
yarn
yarn webpack
```

**Comment by zposten** [comment] 2020-03-31 22:45
Taking inspiration from [this comment](https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020) in a different sass-loader issue, disabling the `webpackImporter` option seems to work around this issue as well

**Comment by evilebottnawi** [comment] 2020-04-01 10:07
PR welcome

**Comment by evilebottnawi** [comment] 2020-04-01 10:07
Anyway my recommendation to avoid using `includePaths`, because it is incompatibility with yarn pnp

**Comment by evilebottnawi** [comment] 2020-04-13 12:35
Duplicate of #804 (fixed in master, writing tests to avoid regressions), thanks for the issue

**Closed by evilebottnawi** 2020-04-13 12:35 UTC
