### ISSUE TITLE
can't load image

### ISSUE THREAD

**Issue by adamchuan** [webpack-contrib/sass-loader#274] opened 2016-08-30 13:39 UTC
this is my code, it generate css background in a list circle。
`$colors-list : red, orange, yellow, purple; 
    @each $color in $colors-list {
        .numcolor-#{$color} { 
            .icon-x {
                background-image:url(#{"./images/" + $color + "_x.png"});
            }

```
        @for $i from 0 through 9 {
            .num#{$i} {
                background-image: url(#{"./images/" + $color + $i + ".png"});
            }
        } 
    }
```

 }`

Here's my errors:
`ERROR in ./~/css-loader!./~/sass-loader!./src//assets/index.scss
    Module not found: Error: Cannot resolve directory './images' in  gifteffect\assets
     @ ./~/css-loader!./~/sass-loader!./src/assets/index.scss 6:4492-4512 6:4587-4607 6:
4681-4701 6:4775-4795 6:4869-4889 6:4963-4983 6:5057-5077 6:5151-5171 6:5245-5265 6:5339-5359 6:5433-5453
`
Please, help to solve the current problem.

**Comment by thescientist13** [comment] 2016-10-05 03:09
@adamchuan 
The SASS file with the background image, are you using `@import` to load that into another SASS file?  

If so, I think the issue is that the relative path of the background image cannot be resolved relative to the path of the SASS file `@import`ing the parent SASS file.

**Comment by evilebottnawi** [comment] 2017-05-03 11:59
@adamchuan @thescientist13 seems using `relative` url, see docs about https://github.com/webpack-contrib/sass-loader#problems-with-url.

Not active more 90 days. Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!

**Closed by evilebottnawi** 2017-05-03 11:59 UTC

**Comment by thescientist13** [comment] 2017-05-03 12:48
thanks @evilebottnawi !  will look into that.  thanks!
