### ISSUE TITLE
Versions after 8 of sass-loader fail to resolve "@import" statements.

### ISSUE THREAD

**Issue by LeopoldLerch** [webpack-contrib/sass-loader#888] opened 2020-09-08 12:11 UTC
I tried with node-sass and dart-sass. 

- Operating System: Win10
- Node Version: 12
- NPM Version: 6.13
- webpack Version: 4
- sass-loader Version: 9/10

### Expected Behavior

Files should be found and imported 

### Actual Behavior

SassError: Can't find stylesheet to import.
  ╷
1 │ @import "~/scss/variables";
  │         ^^^^^^^^^^^^^^^^^^
  ╵

### Code
webpack config:
`context: __dirname + "/src",`

and rule:
```         {
            enforce: "pre",
            test: [/\.scss$/, /\.css$/],
            exclude: [/node_modules/, /masterpage\.css/, /\.global\./i],
            use: [
                MiniCssExtractPlugin.loader,
                {
                    loader: "@teamsupercell/typings-for-css-modules-loader",
                    options: {
                        disableLocalsExport: true
                    }
                },
                {
                    loader: 'css-loader',
                    options: {
                        importLoaders: 1,
                        modules: {
                            localIdentName: "[local]--[hash:base64:5]",
                            exportLocalsConvention: "camelCase",
                        },
                        url: false,
                    }
                },
                "sass-loader"
            ],
        },
```

### How Do We Reproduce?

Might be due to the fact, that my webpack-context is a subfolder ("/src") of the actual workspace-path. However, this is set in the context of webpack (like shown above) and worked until and including version 8. Replacing `@import "~/scss/variables"` with `@import "~scss/variables";` doesn´t make a difference either.

**Comment by evilebottnawi** [comment] 2020-09-08 13:10
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Without reproducible steps I can't help, using `@import "~/scss/variables";` is invalid 
you should use `@import "~scss/variables";`

**Comment by LeopoldLerch** [comment] 2020-09-08 13:34
updated my topic, maybe that can help (removing the slash after the tilde did not make a difference)

**Comment by evilebottnawi** [comment] 2020-09-08 13:39
@LeopoldLerch I can't reproduce, please create reproducible test repo

**Comment by LeopoldLerch** [comment] 2020-09-08 14:10
okay, I think i figured it out.

using the filename WITH extension works

`@import "~/scss/variables.scss";`

If I omit the extension, it cannot find the file (the slash after the tilde does not make a difference). We use the import inside scss-files so that we can reuse stuff from other ones.

Do i have to update the code or is there anything else I could do to stay on track with the evolution of sass-loader?

**Comment by evilebottnawi** [comment] 2020-09-08 14:32
@LeopoldLerch hm, I think it is bug on `sass-loader` side, can you provide simple example, maybe even create minimum reproducible test repo? It should work without extensions

**Comment by LeopoldLerch** [comment] 2020-09-08 15:14
well, have to come back to that later. Too many errors for now, have to switch back to version 8 to go on with the project. 
However, did not find the reason yet, as it does not behave the same for every file. You see this file:

`@import "postsans";
@import "variables";
@import "mixins";
@import "animations";
@import "layout";
@import "~Shared/Icon/icon";

@import "~Entries/scss/startpages.scss";
@import "~Entries/BodyStartSeite/styles.scss";
@import "topnav";

@import "~MainComponents/Navigation/localnav";

@import "~Shared/Flyout/flyout";
@import "~Shared/Dialog/styles.scss";
@import "~Shared/PopOver/popover";
@import "~Shared/OverflowBox/overflowbox";
@import "~Shared/SocialShare/socialshare";
@import "~Shared/Formfields/form.scss";

@import "~MainComponents/Comments/styles.scss";
@import "formDB";
@import "~MainComponents/Berichtsportal/scss/reportDB.scss";

@import "~Shared/FolderViewer/styles.scss";
@import "~MainComponents/BildUpload/styles.scss";

@import "~MainComponents/SharePointViewTools/styles.scss";

@import "~MainComponents/OskarBubble/styles.scss";
`

All of these are scss-files. However, Some need to be explicitly imported with Extension, some don´t. From this file, it seems, that those, which do have a path and their parent-folder does not have the same name like the file, they need the extension. But I might be wrong also.

**Comment by evilebottnawi** [comment] 2020-09-08 15:19
@LeopoldLerch something wrong with your configuration, there is not big changes in resolving between 8-10, only fixes

**Comment by evilebottnawi** [comment] 2020-09-08 15:20
I can't even reproduce this locally

**Comment by LeopoldLerch** [comment] 2020-09-08 15:22
well, you can see my configuration above. Back to Version 8 and works again

**Comment by evilebottnawi** [comment] 2020-09-08 15:26
@LeopoldLerch can you provide `resolve` (https://webpack.js.org/configuration/resolve/) options?

**Comment by LeopoldLerch** [comment] 2020-09-09 06:12
well, as the same webpack-config with the same source code in the same environment works with version 8, there has to be some, altough maybe very small, difference.

Here are my resolve-options (quite usual, not very spectacular):

`    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".ts", ".tsx", ".js", ".json", ".css", ".scss"],
        plugins: [new TsconfigPathsPlugin()],
    },`

**Comment by evilebottnawi** [comment] 2020-09-09 10:51
Unfortunately, I cannot say what is the reason without a minimum reproducible test repo, we have very many tests and even your examples

**Comment by LeopoldLerch** [comment] 2020-09-09 11:26
Can I provide you my source-code somehow?

**Comment by evilebottnawi** [comment] 2020-09-09 11:39
@LeopoldLerch yes, DM in twitter https://twitter.com/evilebottnawi

**Comment by LeopoldLerch** [comment] 2020-09-09 11:44
I mean I would zip the whole source code with and provide the file to you. Guess I cannot do that via twitter-message

**Comment by evilebottnawi** [comment] 2020-09-09 11:47
@LeopoldLerch You can use zip with password, send a link on google disk and provide password via DM

**Comment by evilebottnawi** [comment] 2020-09-09 14:18
Here was two problems:
- case insensitivity file names, some imports was written `@import "dir/File.scss";`, but file was named `file.scss`
- using `@import "~/dir/file";`, but it is invalid syntax, you should use `@import "~dir/file";` and don't forget to add, if you want to use `~` for resolving from `src` of your project
```
{
  resolve: {
     modules: [path.resolve(__dirname, 'src'), 'node_modules'],
 } 
}

**Closed by evilebottnawi** 2020-09-09 14:18 UTC
