### ISSUE TITLE
sass-loader break the webpack2 whenever encounter the @import

### ISSUE THREAD

**Issue by Guobacai** [webpack-contrib/sass-loader#465] opened 2017-05-25 19:48 UTC
webpack -> 2.6.1
webpack-dev-server -> 2.4.5
sass-loader -> 6.0.5
node-sass -> 4.5.3

I follow the example settings on the readme.
````
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader'
          }
        ]
      }
````

Whenever I start the webpack-dev-server in the gulp, it shows the following non-meaningful error message:
undefined:0

TypeError: undefined is not a function

it looks like this issue is caused by the @import in the scss file:
@import 'app/index/styles'
Whenever I comment out it, it doesn't show above error.

If anyone has any idea on this issue, that would be appreciated.

**Comment by evilebottnawi** [comment] 2017-05-25 20:00
@Guobacai can your show stack trace of error?

**Comment by Guobacai** [comment] 2017-05-25 21:09
@evilebottnawi I tried a few ways to print out the stack trace, but failed.
The webpack doesn't show any stack trace of error. I just show the above error and hang there (It doesn't even exist.)

I found the same issue reported here: https://github.com/shama/webpack-stream/issues/135

If I missed anyway to show the stack trace of error, please advise me.

Thanks @evilebottnawi for your time.

**Comment by evilebottnawi** [comment] 2017-05-25 21:29
@Guobacai be good if your can create minimal test reproducible repo :+1: This will help us understand why it happens

**Comment by thescientist13** [comment] 2017-05-28 16:54
I am seeing this issue as well.  Here is the full output I am seeing
```bash
$ yarn run build
yarn run v0.21.3
$ eslint *.js **/**/*.spec.jsx && webpack --config ./webpack.config.prod.js -p --progress --profile --bail
 10% building modules 0/2 modules 2 active ....com/repo/bc-webapp-2.0/src/vendor.tsWarning: Got empty options
Warning: The 'no-use-before-declare' rule requires type checking

[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/tsconfig.json.

6880ms building modules
5ms sealing
0ms optimizing
0ms basic module optimization
3ms module optimization
1ms advanced module optimization
11ms basic chunk optimization
0ms chunk optimization
8ms advanced chunk optimization
 37% building modules 231/232 modules 1 active ...2.0/src/components/footer/footer.scss
/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/Compilation.js:219
				_this.errors.push(err);
         ^
TypeError: Cannot read property 'errors' of null
    at errorAndCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/Compilation.js:219:10)
    at errorOrWarningAndCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/Compilation.js:251:14)
    at factoryCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/Compilation.js:264:13)
    at factory (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/async/dist/async.js:3838:9
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/async/dist/async.js:996:13)
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/async/dist/async.js:906:16
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/async/dist/async.js:3835:13
    at resolvers.normal.resolve (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onResolved (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/obuckley/Workspace/1000-bc.com/repo/bc-webapp-2.0/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- webpack: 2.5.1
- sass-loader: 6.0.5

**Comment by evilebottnawi** [comment] 2017-05-28 17:11
@thescientist13 seems not related to `sass-loader`. Problems in `webpack/lib/Compilation.js:219:10`, maybe something wrong with `ts-loader` loader?

**Comment by thescientist13** [comment] 2017-05-28 17:35
thanks @evilebottnawi , yeah I'm reviewing [another project](https://github.com/thegreenhouseio/react-webapp-seed) of mine that has this working and so just trying to diff the two.  A very barebones example with just `babel-loader` works, so yes, appears to be something not related to sass-loader specifically.  Will continue debugging a little bit more and post back if I can find anything.

**Comment by thescientist13** [comment] 2017-05-29 15:19
It seemed in my case I was getting this error in regards to using `@fontface` in my _.scss_ file.  When adding them back in and using **url-resolve-loader**, there were no more errors.

**Comment by borela** [comment] 2017-06-01 04:43
I believe you need to add the directories to the `includePaths` to help resolve the files like so https://github.com/ctrine/webpack-settings/blob/master/packages/shared/src/rules/sass-module.js

**Comment by michael-ciniawsky** [comment] 2017-06-01 14:12
This seems to be resolved, closing for now, but feel free to reopen if still regressions related to `sass-loader` :)

**Closed by michael-ciniawsky** 2017-06-01 14:12 UTC
Labels: flag: Needs more info
