### ISSUE TITLE
Webpack Uglify plugin puts sass-loader into compression mode with no obvious way to turn it off

### ISSUE THREAD

**Issue by jvanderberg** [webpack-contrib/sass-loader#299] opened 2016-11-06 15:33 UTC
Recently we deployed a new sass configuration to production and found that the emitted CSS was mangled.  Removing the Uglify plugin from our production build fixed this.  What's odd is that  Uglify doesn't touch CSS, it does however put other loaders into the 'minimize' mode.

I was eventually able to track down the issue to the sass-loader's compression setting.

In index.js here's the only reference to minification or compression:
```
    if (!sassOptions.outputStyle && this.minimize) {
        sassOptions.outputStyle = 'compressed';
    }
```
Based on this code, sass-loader doesn't have an obvious way to turn off compression when Uglify is used. 'this.minimize' appears to always be true if the Uglify plugin is used, and sass-loader makes no attempt to inspect its options for minimize=false, so you can use sass-loader?minimize=false or sass-loader?-minimize to no effect.

But, there is a workaround, sass-loader?outputStyle=uncompressed does disable the sass-loader's compression and fixes our production build. 'uncompressed' probably isn't even a valid option, but it does effectively disable compression.

It would be nice if sass-loader explicitly respected the 'minimize' query string option.  This might be less of an issue with Webpack 2.

**Comment by silviogutierrez** [comment] 2017-01-03 01:26
I had the same issue: odd pieces of my SASS files were being stripped out when building with `-p`. In webpack.

In my case, I fixed it by adding `-minimize` to the *css-loader*, not the SASS loader.

Like so:

```js
            {
                test: /\.scss$/,
                loaders: ["style-loader", "css-loader?-minimize", "sass-loader"],
            },
```

Very odd.

**Comment by chartinger** [comment] 2017-01-26 15:04
@jvanderberg thank you so much. I spent half a day trying to figure out why the production css was messed up. Nearly all issues i found about this topic were about css-loader and cssnano but no configuration had any effect. Nor did -minimize on the sass-loader. Your outputStyle workaround did the trick.

**Comment by jvanderberg** [comment] 2017-01-26 16:47
@silviogutierrez I'd thought we'd tried just about every combination of flag on every loader we could think of.  I may revisit and see, but most likely I think our next big change will be Webpack 2, and it will likely fix this by not putting loaders into minimize mode by default.

**Comment by evilebottnawi** [comment] 2017-05-03 12:19
@jvanderberg @silviogutierrez @chartinger Is there a problem or has it been solved? If not can your create minimal reproducible test repo?

**Comment by chartinger** [comment] 2017-05-03 12:55
For me the issue was solved with the output workaround back then. [I did not run into this issue in my recent projects]

**Comment by evilebottnawi** [comment] 2017-05-03 13:19
@chartinger can you provide what do your done, it is help to other people :smile:

**Comment by chartinger** [comment] 2017-05-03 13:56
Just like in the original post

> But, there is a workaround, sass-loader?outputStyle=uncompressed does disable the sass-loader's compression and fixes our production build. 'uncompressed' probably isn't even a valid option, but it does effectively disable compression.

I think this ticket is more about having an "official" way to do the same, but helped me solve the problem with the given "unsupported" method.

**Comment by jvanderberg** [comment] 2017-05-04 12:40
@evilebottnawi I think the underlying issue is that there's something broken in the minification when sassLoader.outputStyle == 'compressed'.  I don't know how to reproduce the issue as it's pretty difficult to debug minimized CSS output (at least for me).  But that's beside the point of this case really.  Even if what specific bug I am encountered were fixed, I imagine in future there are always going to be bugs or edge cases with minification, and it would be nice if there were an 'official' way to disable minification.  Maybe my outputStyle setting usage is official, but I fear that perhaps future releases will change/break this behavior.

I don't think we've updated the versions we are using in awhile.  We should probably revisit this and see if any of the issues have resolved.

**Comment by evilebottnawi** [comment] 2017-05-04 13:10
@jvanderberg `sass-loader` doesn't `minify` code, this do `css-loader` using `cssnano` or `postcss-loader` with `cssnano` plugin. We are trying to reduce the number of unanswered problems, since it is difficult where there is a bug and where not and where it related to the loader (here `sass-loader`) and where not. We should reproduce bug or close issue. If bug to happen again, we can reopen this issue or create a new with more relevant data. We just try to do `webpack` is better for you :smile:

**Comment by jvanderberg** [comment] 2017-05-05 21:31
Yes, in my troubleshooting I assumed the minification issue lies lower in the stack.  But the piece of the stack turning on minification is the sass-loader, and it ignores the configuration flags that usually disable minification.

The following webpack config results in css minification, which breaks our build (yes, not your fault I know)
			{
				test: /\.s?css$/,
				loaders: [
					'style-loader',
					'css-loader?-minimize',
					'postcss-loader',
					'sass-loader'
				]
			},

This does not result in minification and allows our production build to function:
			{
				test: /\.s?css$/,
				loaders: [
					'style-loader',
					'css-loader?-minimize',
					'postcss-loader',
					'sass-loader?outputStyle=uncompressed'
				]
			},

My hope would be that sass load could make some simple changes to allow the standard flag css-loader uses to disable minification, or to somehow pick up on css-loaders configuration.  I had to read the source code to figure out the outputStyle flag, and I am not at all sure it's going to work in future versions.  Note, we are using 0.23.1

**Comment by evilebottnawi** [comment] 2017-05-23 10:04
@jvanderberg your use `webpack` `v2` and latest versions of loader?

**Comment by jvanderberg** [comment] 2017-05-23 15:05
We have not moved to Webpack 2 yet, and are using the version listed in my previous comment.  I suspect webpack 2 will fix things because it does not automatically put plugins into minimize mode when UglifyJSPlugin is used.

**Comment by evilebottnawi** [comment] 2017-05-23 15:09
@jvanderberg Closed the issue. if your will get this error after moving to `webpack` `v2` feel free to reopen. Thanks!

**Closed by evilebottnawi** 2017-05-23 15:09 UTC
Labels: flag: Needs more info
