### ISSUE TITLE
Dart Sass without fibers should use renderSync instead of render

### ISSUE THREAD

**Issue by filipesilva** [webpack-contrib/sass-loader#701] opened 2019-07-02 15:19 UTC
* Operating System: Windows
* Node Version: 10.16.0
* NPM Version: 6.9.0
* webpack Version: 4.30.0
* sass-loader Version: 7.1.0

### Expected Behavior

When using Dart Sass and not using `fibers`, the `renderSync` method should always be used instead of the `render` method (see https://github.com/sass/dart-sass#javascript-api, https://github.com/webpack-contrib/sass-loader/issues/435#issuecomment-349450103 and https://github.com/sass/dart-sass/issues/744#issuecomment-507429974 for details). Always using `render` has severe performance implications.

### Actual Behavior

The `render` method is always used with Dart sass.

### Code

https://github.com/webpack-contrib/sass-loader/blob/e279f2a129eee0bd0b624b5acd498f23a81ee35e/lib/loader.js#L137-L144

### How Do We Reproduce?

No external reproduction needed. It's in the source code for this package.

**Comment by evilebottnawi** [comment] 2019-07-02 15:28
Thanks for issue, i will investigate this for next major release, i think i will start work on next release at this week, a lot of other issues

**Comment by filipesilva** [comment] 2019-07-02 15:36
SGTM, thanks for looking at it!

**Comment by jhnns** [comment] 2019-07-08 09:38
We could make it configurable via loader options. This pushes the responsibility/complexity back to the user. The problem is that the sass-loader has no clue if your project uses any custom importer where the async API is necessary.

I should also mention that compiling something synchronously is one of the worst things you can do in a webpack build. In a regular webpack build there are hundreds of async module builds simultaneously. If you do something synchronously, it will pause all other module builds. I'm pretty sure that most people will get worse performance results if they do something synchronously 😁

**Comment by filipesilva** [comment] 2019-07-08 10:57
I think configurable makes sense if the plugin cannot determine it. I can compare performance numbers if you guide me a little bit on how I can change it in my node modules. I tried to change it myself in https://github.com/sass/dart-sass/issues/744#issuecomment-507245355 but it looks like I was missing something.

**Comment by nex3** [comment] 2019-07-10 22:03
> We could make it configurable via loader options. This pushes the responsibility/complexity back to the user. The problem is that the sass-loader has no clue if your project uses any custom importer where the async API is necessary.

This would make sense, but the *default* should still probably be running synchronously (which means WebPack's custom importer should be synchronous as well).

> I should also mention that compiling something synchronously is one of the worst things you can do in a webpack build. In a regular webpack build there are hundreds of async module builds simultaneously. If you do something synchronously, it will pause all other module builds. I'm pretty sure that most people will get worse performance results if they do something synchronously :grin:

**Comment by evilebottnawi** [comment] 2019-07-10 22:14
> This would make sense, but the default should still probably be running synchronously (which means WebPack's custom importer should be synchronous as well).

Int theory it is possible https://github.com/webpack/enhanced-resolve#resolve (we need use `sync`), but here can be other problem - it is decrease sass compilation time, but decrease webpack compilation time, no golden way here

**Comment by nex3** [comment] 2019-07-10 23:08
The overhead of running Sass asynchronously tends to range between 3 and 4x the total compilation time for large projects, not to mention the memory overhead that @filipesilva is running into. This dwarfs file IO time, which means it's also likely to dwarf the benefits you'd get from increased parallelism while waiting on file IO.

**Comment by semiromid** [comment] 2021-04-28 07:00
Hi @nex3 !

Thank you for your work!

1 - Are you considering caching? To increase the performance of file processing
2 - sass.renderSync - Is it recommended?

**Comment by nex3** [comment] 2021-04-28 22:44
> 1 - Are you considering caching? To increase the performance of file processing

Filesystem operations aren't the bottleneck here. The issue, as I explained above, is the overhead of going back to the event loop for every method call in asynchronous mode.

> 2 - `sass.renderSync` - Is it recommended? I mean [Dart-Sass](https://sass-lang.com/dart-sass) for JS `npm install sass --save-dev`.

Yes, `renderSync()` is recommended for Dart Sass.

**Comment by semiromid** [comment] 2021-04-29 03:33
@nex3 
Thank you!

Can I set your avatar in my plugin?

**Comment by nex3** [comment] 2021-04-29 20:23
I'd prefer it if you didn't.

**Comment by semiromid** [comment] 2021-04-30 01:05
> I'd prefer it if you didn't.

@nex3 Ok. I will not add a photo of your avatar. It was just needed for the quote you made. Then I'll just add your nickname.



Here are these quotes

> The logic of compiling Sass—which is by far the bottleneck of Sass compilation—is inherently synchronous. There's nothing about parsing strings or manipulating ASTs that can be done out-of-process, so making it asynchronous doesn't buy you anything in terms of speed (and in fact makes it much slower because it has to bounce back to the event loop all the time). The only reason it has an asynchronous mode at all is to support asynchronous plugins.

> The overhead of running Sass asynchronously tends to range between 2x and 3x the total synchronous compilation time for large projects, not to mention the memory overhead that @filipesilva is running into. This dwarfs file IO time, which means it's also likely to dwarf the benefits you'd get from increased parallelism while waiting on file IO.

**Comment by alexander-akait** [comment] 2021-09-07 14:00
We can't use sync api because we need resolve your `@import`/`@use` and etc, it will bring a big losing of perf

**Comment by niksy** [comment] 2021-09-07 14:03
> We can't use sync api because we need resolve your `@import`/`@use` and etc, it will bring a big losing of perf

This is still developer/user issue and it’s something that could be mentioned in documentation. Currently there really isn’t any good way forward other than opt-in to sync API and deal with consequences.

**Comment by alexander-akait** [comment] 2021-09-07 14:04
We can't enable sync api, resolver are always async

**Comment by niksy** [comment] 2021-09-07 14:06
> We can't enable sync api, resolver are always async

Do you mean Webpack resolver or Sass resolver? Because Webpack enhanced resolve has sync option IIRC.

**Comment by shantanu2307** [comment] 2023-10-31 05:56
> 1 - Are you considering caching? To increase the performance of file processing

Are we not caching the results?

**Comment by alexander-akait** [comment] 2024-07-26 16:55
I want to close this issue, because we can't use `renderSync`, but if you need improve perf just use `sass-embedded` and `modern-compiler`, async compilation will be faster and incremental builds will be faster (faster then with `sync`)

Anyway feel free to feedback

**Closed by alexander-akait** 2024-07-26 16:55 UTC
Labels: type: Feature, status: Needs triage
