### ISSUE TITLE
Cannot import scoped node_module packages

### ISSUE THREAD

**Issue by levithomason** [webpack-contrib/sass-loader#293] opened 2016-10-26 18:01 UTC
When importing a scoped node_module package with the tilde syntax:

``` scss
@import '~@technologyadvice/radiant';
```

The following error is produced:

```
Module build failed: 
@import '~@technologyadvice/radiant';
^
      File to import not found or unreadable: ~@technologyadvice/radiant
```

I moved the module to `node_modules/radiant`, updated its `package.json` fields to remove its scoping, and then `@import '~radiant';` and it worked.  My guess is that the `@` is causing some issue.

**Comment by jhnns** [comment] 2016-10-27 15:31
When you write

```
@import '~@technologyadvice/radiant';
```

webpack will search at `./node_modules/@technologyadvice/radiant` for the module – exactly like dependencies in node are resolved. What were you expecting?

**Comment by levithomason** [comment] 2016-10-29 03:13
That is exactly what I was expecting. The module is installed at the path you noted but it is not found. 

When installing scope modules, their package name is scoped and they are installed to the scope folder (@technologyadvice). The only way I could get this to work was to move the module up out of the scope folder into the root of node_modules.

**Comment by jhnns** [comment] 2016-11-07 23:46
What does the `main` field of the radiant's `package.json` say?

**Comment by levithomason** [comment] 2016-11-10 01:58
`"main": "dist/css/radiant.css",`

**Comment by levithomason** [comment] 2016-11-10 01:59
Again, the curious thing here is that it works just fine when it is not in a `@technologyadvice` scoped folder.  No changes are required to the package nor the config in that case, it just works.  Only when the module is in the scoped folder does it fail to find it.

**Comment by jacobgunnarsson** [comment] 2017-02-14 14:51
@jhnns We are encountering this exact problem as of `6.0.0`. Can confirm all of @levithomason's observations. 

In addition; the scoped node_module import syntax works when importing using a reference to a specific file, i.e. `@import "~@styles/variables` is not found whereas `@import "~@styles/variables/src/main"` is. `@styles/variables/package.json` contains `main: 'src/main.scss'`.

Any thoughts or updates? Thanks!

**Comment by jhnns** [comment] 2017-02-14 15:16
I assume that this is a webpack problem because the sass-loader is not resolving it. Could you create a minimal example that reproduces the error? Just commit a small example node_modules folder with the folder structure. Try to remove as much as possible.

**Comment by Kikobeats** [comment] 2017-04-12 11:55
Same problem using [material components web](https://github.com/material-components/material-components-web)

Looks like the `@` char is not matching as condition for resolve the local module.

**Comment by evilebottnawi** [comment] 2017-05-03 18:20
Close in favor https://github.com/webpack-contrib/sass-loader/issues/293 (duplicate) and already have PR https://github.com/webpack-contrib/sass-loader/pull/447.

Please feel free to reopen (or create new issue) if this doesn't related to your issue. Thanks!

**Closed by evilebottnawi** 2017-05-03 18:20 UTC
