### ISSUE TITLE
Bug in path resolution introduced in v9.0.x (import loop detected where there is no loop)

### ISSUE THREAD

**Issue by birdofpreyru** [webpack-contrib/sass-loader#863] opened 2020-07-04 23:44 UTC
- Operating System: Ubuntu 18.04
- Node Version: v12.18.2
- NPM Version: v6.14.5
- webpack Version: v4.43.0
- sass-loader Version: v9.0.1

### Actual Behavior

On an existing codebase, after upgrade from `sass-loader@8.0.2` to `v9.0.1` I am getting the error:
```
SassError: An @import loop has been found:
               src/styles/global.scss imports src/styles/mixins.scss
               src/styles/mixins.scss imports node_modules/@dr.pogodin/react-utils/mixins.scss
               node_modules/@dr.pogodin/react-utils/mixins.scss imports src/styles/mixins.scss
```
There is not loop though, just SCSS files with the same names on the same routes in a library, and in the host codebase, _i.e._ such file structure, which worked fine with `sass-loader <= 8.0.2`:
```
/src
  /styles
    - global.scss
    - mixins.scss
/node_modules
  /@dr.pogodin
    /react-utils
      - mixins.scss
      /src
        /styles
          - mixins.scss  
```

I guess, I'll come with extra details later. Posting the issue in case from the issue description you may know what changes in the latest versions could cause it.

**Comment by birdofpreyru** [comment] 2020-07-05 00:04
Narrowed the issue down to the commit aeb86f078d01460990aa8b06fce81b6fe7e3fbb6: the issue appears with that commit, and everything works fine with the previous commit. Considering the commit is named `fix: resolution logic (#839)`, I guess that fix actually breaks stuff, and also my issue is a legit bug in `sass-loader`.

**Comment by evilebottnawi** [comment] 2020-07-06 13:37
Maybe you can create reproducible test repo? it is hack to solve architectural problems with `importer` and `includePaths`. It is very strange, can you try to compile it without `sass-loader`?

**Comment by birdofpreyru** [comment] 2020-07-06 20:45
@evilebottnawi Sure just try to build this: https://github.com/birdofpreyru/react-starter with the latest `sass-loader`.

If you just clone, `npm install && npm run dev` - it works good.
If you then `npm install sass-loader@latest && npm run dev` - it fails

**Comment by birdofpreyru** [comment] 2020-07-06 20:50
Regarding the options, I don't do anything special. Here is `sass-loader` in my Wepback config template: https://github.com/birdofpreyru/react-utils/blob/master/config/webpack/app-base.js#L239-L244

**Comment by evilebottnawi** [comment] 2020-07-07 11:51
Here interesting case, by default `sass` tries to resolve `process.cwd() + 'src/styles/mixins'` - https://github.com/sass/dart-sass/blob/master/lib/src/importer/node/implementation.dart#L152, we emulate this behavior, here is the problem:
1. We have `process.cwd() + 'src/styles/mixins'`
2. We have `@import "src/styles/mixins";` in `@dr.pogodin/react-utils/mixins.scss`

I will investigate this problem more deeply

**Comment by birdofpreyru** [comment] 2020-07-07 12:00
Hmm... but, why does it do `process.cwd() + 'src/styles/mixins'`? According to SASS docs, if I got them correctly:

> Imports will always be resolved relative to the current file first, though. Load paths will only be used if no relative file exists that matches the import. This ensures that you can’t accidentally mess up your relative imports when you add a new library.

https://sass-lang.com/documentation/at-rules/import#load-paths

**Comment by evilebottnawi** [comment] 2020-07-07 12:18
@birdofpreyru Don't know, because https://github.com/sass/dart-sass/blob/master/lib/src/importer/node/implementation.dart#L152, `p.absolute(path)` return `absolute path` - https://github.com/dart-lang/path/blob/master/lib/path.dart#L119, maybe I wrong, doing debugging

**Comment by evilebottnawi** [comment] 2020-07-07 13:07
Bug, we don't need to emulate `process.cwd() + 'src/styles/mixins'`, when url contains empty or file schema `https://github.com/sass/dart-sass/blob/master/lib/src/importer/node/implementation.dart#L98`

**Comment by evilebottnawi** [comment] 2020-07-07 14:00
@birdofpreyru Looks like it is bug on `node-sass`, because migration on `sass` (`dart`) solve this problem, we strongly recommend do it [here](https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0). Not sure it can be fixed, because it is the limitation, `node-sass` has many of them

**Comment by evilebottnawi** [comment] 2020-07-07 14:14
Found changes:
1. `node-sass` call our `importer` before relative resolving, context resolving, includePaths resolving and `SASS_PATH` env variable resolving - https://github.com/sass/libsass/blob/16f76e2cd6cebf0a31f579a40e635c309109e4db/src/parser.cpp#L357
2. `sass` (`dart`) call our `importer` after relative resolving - https://github.com/sass/dart-sass/blob/master/lib/src/importer/node/implementation.dart#L72

No information about these changes in docs

/cc @nex3

**Comment by evilebottnawi** [comment] 2020-07-07 15:10
Found workaround, path release will be today

**Comment by birdofpreyru** [comment] 2020-07-07 15:16
Awesome! Many thanks @evilebottnawi !

**Closed** 2020-07-07 15:28 UTC

**Comment by nex3** [comment] 2020-07-07 19:22
> Found changes:
> 
> 1. `node-sass` call our `importer` before relative resolving, context resolving, includePaths resolving and `SASS_PATH` env variable resolving - https://github.com/sass/libsass/blob/16f76e2cd6cebf0a31f579a40e635c309109e4db/src/parser.cpp#L357
> 2. `sass` (`dart`) call our `importer` after relative resolving - https://github.com/sass/dart-sass/blob/master/lib/src/importer/node/implementation.dart#L72
> 
> No information about these changes in docs
> 
> /cc @nex3

The [JS API `importer` docs](https://sass-lang.com/documentation/js-api#importer) describe this behavior, including the node-sass incompatibility if you click the drop-down arrow on "Compatibility (Import order)".

**Comment by evilebottnawi** [comment] 2020-07-08 10:44
@nex3 thanks, I never knew that this arrow opens :smile:
